### PR TITLE
add: glacier-settings_es.ts

### PR DESCRIPTION
**Pull request by carlosgonz0**

### CODE REVIEW

**Comment by jmlich** [comment]
@neochapay  please ping me next time when merging other languages than english. The transifex need manual sync.

**Comment by neochapay** [comment]
Ok

**Comment by jmlich** [comment]
@carlosgonz0 

It seems the translation is malformed:

```
Some files didn’t sync with Transifex:
/translations/glacier-settings_es.ts
Error while uploading translation: b"Could not import file: Your file doesn't seem to contain valid xml: not well-formed (invalid token): line 2, column 2!"
/translations/glacier-settings_en.ts
Error while uploading translation: b'Cannot update the source language'
```

**Comment by jmlich** [comment]
fixed in 627aa98c21d8bf453fca858105665c2fc93ac8de

**Pull request merged**
